### ISSUE TITLE
Not able to select points

### ISSUE THREAD

**Issue by Bassi-git** [stemangiola/tidygate#14]
Hi,
I would love to use your package but somehow I am not able to make it work. It would be great if you could help me understand, what is going wrong here. When I try the follwoing example I always get this error:

ggplot(tidygate_data)+geom_point(mapping = aes(x=Dim1,y=Dim2))
> 
> tidygate_gate <-
+   tidygate_data %>%
+   mutate( gate = gate_chr( Dim1, Dim2 ) )
Error: Problem with `mutate()` column `gate`.
ℹ `gate = gate_chr(Dim1, Dim2)`.
x Must extract column with a single valid subscript.
x Subscript `var` has size 0 but must be size 1.
Run `rlang::last_error()` to see where the error occurred.

Backtrace:
  1. tidygate_data %>% mutate(gate = gate_chr(Dim1, Dim2))
 26. dplyr:::pull.data.frame(., color_hexadecimal)
 27. tidyselect::vars_pull(names(.data), !!enquo(var))
 28. tidyselect:::pull_as_location2(loc, n, vars)
 36. vctrs::num_as_location2(i, n = n, negative = "ignore", arg = "var")
 37. vctrs:::result_get(...)

When I run the second part uncluding gate_chr, a new plot appears in the plot area (I am using RStudio), but it is empty.

Let me know if you need any other info!
Thanks for your help!

**Comment by stemangiola** [comment]
Hello,

can you please confirm that you tried to reproduce the README example replicating the GIF video, and that did not work?

**Comment by Bassi-git** [comment]
Hi,
Thanks for the quick answer! 
Maybe I also don't understand the README completely. How do you arrive at the interactive plot?

What I did is, I just produced a simple ggplot with

ggplot(tidygate_data)+geom_point(mapping = aes(x=Dim1,y=Dim2))
This plot shows up normally.

Then I ran

tidygate_gate <-
  tidygate_data %>%
  mutate( gate = gate_chr( Dim1, Dim2 ) )

Another plot opens in the plot area but it is empty, I cannot select anything and the error appears.

I hope this clarifies things. Thanks a lot for your help!

**Comment by stemangiola** [comment]
Try to read the new README 

https://github.com/stemangiola/tidygate

and let me know how you go. It is more clear?

**Comment by Bassi-git** [comment]
Hi,
Thank you for updating the README. I was wondering, whether I was missing something but that's not the case. I still have the same problem.
I am inserting below the output of the full script that I ran. After running

tidygate_gate <-
tidygate_data %>%
mutate( gate = gate_chr( Dim1, Dim2 ) )

A plot appears in the plot area, that I know exists because I can export it. But it is completely white and I never get any option to interact with it.

![Screenshot 2021-07-26 at 10 07 22](https://user-images.githubusercontent.com/62747147/126955738-e0e2d419-8585-4281-afd7-775a0c0a6313.png)
![Screenshot 2021-07-26 at 10 07 32](https://user-images.githubusercontent.com/62747147/126955751-64cbeaef-7baa-46c7-94cb-90e6ac0bc2e3.png)
 
Thanks for your help!

**Comment by stemangiola** [comment]
Sorry for that!

It is hard to unit-test an interactive package. 

I have updated the master. Please test again.

**Comment by Bassi-git** [comment]
Great, it works now!
Thanks a lot!
