### ISSUE TITLE
Gate not reflected as I did

### ISSUE THREAD

**Issue by ryotasato2** [stemangiola/tidygate#21]
gates used to work properly but suddenly all the gate I made were shown on the left top with smaller size. Is this a bug or am I doing something wrong? Below is my code and error message. Thx!

harmonized_gated1 <- 
   harmonized_seurat %>%
   mutate(gated1 = tidygate::gate_chr(
     UMAP_1, UMAP_2, .color = seurat_clusters,
     .size = 0.1
   ))
Mark region on plot.
Error in `dplyr::mutate()`:
ℹ In argument: `gated1 = tidygate::gate_chr(...)`.
Caused by error in `map()`:
ℹ In index: 1.
Caused by error in `data[i, 1]`:
! subscript out of bounds
Run `rlang::last_trace()` to see where the error occurred.

![image](https://github.com/stemangiola/tidygate/assets/141756244/4099ca2f-0416-4866-a936-e563626433e6)

**Comment by stemangiola** [comment]
> gates used to work properly but suddenly all the gate I made were shown on the left top with smaller size. Is this a bug or am I doing something wrong? Below is my code and error message. Thx!
> 
> harmonized_gated1 <- harmonized_seurat %>% mutate(gated1 = tidygate::gate_chr( UMAP_1, UMAP_2, .color = seurat_clusters, .size = 0.1 )) Mark region on plot. Error in `dplyr::mutate()`: ℹ In argument: `gated1 = tidygate::gate_chr(...)`. Caused by error in `map()`: ℹ In index: 1. Caused by error in `data[i, 1]`: ! subscript out of bounds Run `rlang::last_trace()` to see where the error occurred.
> 
> ![image](https://user-images.githubusercontent.com/141756244/259154933-4099ca2f-0416-4866-a936-e563626433e6.png)

Rstudio keeps making the interactive backend in base R buggy. Within the #tidyomics community, we would like to change the backend to a more proper one.

https://github.com/orgs/tidybiology/projects/1

Chances are if you use another Rsrudio, from your laptop, for example it would work. Or update Rstudio.

Or contribute to changing the backend! It is a very nice project. The new backend should improve efficiency and scalability as a separate goal.

https://github.com/stemangiola/tidygate/issues/20

**Comment by LiNk-NY** [comment]
@ryotasato2 
Do you have a reproducible example that we can run? It would kickstart any movement in this space. Thank you!

**Comment by stemangiola** [comment]
This is the issue in the Rstudio repository

https://github.com/rstudio/rstudio/issues/10025
https://github.com/rstudio/rstudio/issues/12682

An option could be to use a more modern interactive gating library; the the folks in Rstudio seem not to be so responsive with this.

**Comment by stemangiola** [comment]
New interface with modern visualisation, which avoid this issue is coming.
