### ISSUE TITLE
poll answer wrong :(

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/tidygate#6]
For the poll 5 the correct answer is 

pbmc1_10x_v3_ATGGATCTCATGCCAA

**Comment by mblue9** [comment]
That's ok we haven't put the correct answer anywhere yet (I removed them from the doc) so all good. 
Btw think you meant to put this in the workshop repo :)

**Comment by stemangiola** [comment]
I am pretty sure the right answer was not within the options XD

True wrong repo!

**Comment by mblue9** [comment]
> I am pretty sure the right answer was not within the options XD

I checked and it is
